config/routes.rb
Hacksighter1::Application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :sightings do
    resources :comments
  end

  resources :topics

  root to: 'sightings#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :sighting_id

  belongs_to :sighting
  belongs_to :user
  
  validates :body, presence: true

end

app/models/photo.rb
class Photo < ActiveRecord::Base
 
 attr_accessible :image # attr_accessible :title, :body

 belongs_to :sighting

 has_attached_file :image,
	  	styles: {
	  		thumb: '100x100>',
	  		small: '150x150>',
	  		medium: '200x200>',
	  		large: '300x300>'
	  	},
	  	storage: :s3, s3_credentials: {
	  		access_key_id: "AKIAJ3YA3T7EJX4HPKCA",
  			secret_access_key: "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",
  			bucket: 'Hacksighter'
	  	}

end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  attr_accessible :location, :longitude, :latitude, :topic_id, :photos_attributes, :sighted_at, :sighted_date, :sighted_time, :description
  geocoded_by :location
  after_validation :geocode, :if => :location_changed?
	
	has_many :photos
  	accepts_nested_attributes_for :photos

  	belongs_to :user
  	has_many :comments
  	belongs_to :topic 

	validates :location, presence: true
	validates :user, presence: true
	validates :sighted_at, presence: true

	acts_as_gmappable :process_geocoding => false

	
	def gmaps4rails_address
	 	"#{longitude}, #{latitude}" #describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki "#{self.street}, #{self.city}, #{self.country}" 
	end

	# def sighted_at=(date)
	# 	self[:sighted_at] = Time.zone.parse(date)
	# end


	# def gmaps4rails_marker_picture
	#          {
	#           "picture" => "/assets/led.gif",
	#           "width" => '35',
	#           "height" => '51'
	#          }
	# end

	def self.recent5
		Sighting.order("sighted_at desc").limit(5)
	end


	# Setting Active Record to make a Datetime that can be entered in viewer
	# Code below is modified "attr_accessor", so the default time and date is in the fields of edit
	
	def sighted_date
		if @sighted_date
			@sighted_date
		elsif sighted_at
			sighted_at.to_date
		end
	end

	def sighted_date=(value)
		@sighted_date = value
	end

	def sighted_time
		if @sighted_time
			@sighted_time
		elsif sighted_at
			sighted_at.strftime("%I:%M%p")
		end
	end

	def sighted_time=(value)
		@sighted_time = value
	end

	before_validation :set_sighted_at #ALMOST ALWAYS DO CALLBACK BEFORE_VALIDATION, NOT BEFORE_SAVE

	# private
	def set_sighted_at
		if @sighted_date.present?
			self[:sighted_at] = Time.zone.parse("#{@sighted_date} #{@sighted_time}")
		end
		if self[:sighted_at].blank?
			self[:sighted_at] = Time.zone.now
		end
	end

	def sighted_at
		self[:sighted_at] || self.created_at
	end


	# def sighted_date
	# 	sighted_at.to_date
	# end

	# def sighted_time
	#     sighted_at.strftime("%I:%M%p")
	# end


end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :name

  #has_many :sightings
	has_many :sightings, :order => "sighted_at ASC"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:twitter]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  

  # attr_accessible :title, :body

  has_many :sightings
  has_many :comments

  def email_required?
  	uid.blank? 
  end

  def password_required?
  	uid.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_filter :authenticate_user!

	def create
		sighting = Sighting.find(params[:sighting_id])
		@comment = sighting.comments.build(params[:comment])
		@comment.user = current_user
		if @comment.save
			redirect_to sightings_path
		else
			render 'new'
		end
	end


end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController

	before_filter :authenticate_user!, except: [:index]

	def index
		@q = Sighting.search(params[:q])
		if params[:q].present?
			@sightings = @q.result
		elsif params[:topic].present?
			@sightings = Sighting.includes(:comments).order(:sighted_at).where(topic_id: params[:topic])
		else
			@sightings = Sighting.includes(:comments).order(:sighted_at).all
		end
		
		@sightings_all = Sighting.includes(:comments).order(:sighted_at).all

		@users = User.all

		@current_user = current_user
	 	
		@topics = Topic.all

		@sightings_recent5 = Sighting.recent5

		# Try to implement different markers

		
		@sighting_last=@sightings.last
			@json1 = @sighting_last.to_gmaps4rails do |sighting, marker|

					  marker.picture({
					                  :picture => "http://www.google.com/intl/en_us/mapfiles/ms/micons/red-dot.png",
					                  :width   => 32,
					                  :height  => 32
					                 })
					
					  marker.infowindow render_to_string(:partial => "/sightings/infowindow", :locals => { :sighting => sighting})
					  marker.json({:when => sighting.sighted_at.to_s})
			end unless @sightings.length == 0		
		
			#@sightings_rest = @sightings - @sightings_last
			#@sighting_rest = @sighting.where(id: ((first)..(@sightings.last.id-1))) 

		@sighting_rest = @sightings.length > 0 ? @sightings - [@sighting_last] : @sightings
			@json2= @sighting_rest.to_gmaps4rails do |sighting, marker|

					  marker.picture({
					                  :picture => "http://www.google.com/intl/en_us/mapfiles/ms/micons/blue-dot.png",
					                  :width   => 32,
					                  :height  => 32
					                 })

					  marker.infowindow render_to_string(:partial => "/sightings/infowindow", :locals => { :sighting => sighting})
					  marker.json({:when => sighting.sighted_at.to_s})
					end
		

		@json = ((@json1? JSON.parse(@json1) : []) + JSON.parse(@json2)).to_json

	

# topics = [
# {id: 1, name: "Rob ford", count: 10},
# {id: 2, name: "bike acc", count: 4}
# ]

# count: 4 >>>>> count: Sighting.where(topic_id: topic.id).count


# Look for ruby method COLLECT


		# if params[:user_id]
		# 	@sightings = Sighting.where(user_id: params[:user_id])
		# else
		# 	@sightings = Sighting
		# end
		# @sightings = @sightings.includes(:comments)
	end

	def new
		@sighting = Sighting.new
		@photos = 3.times.map{@sighting.photos.build}
		
	end

	def create
		@sighting = current_user.sightings.build(params[:sighting])
		#@sighting = Sighting.new(params[:sighting])
		if @sighting.save
			redirect_to sightings_path
		else
			render :new
		end
	end

	def edit
		@sighting = Sighting.find(params[:id])
		@json = Sighting.find(params[:id]).to_gmaps4rails
		@photos = 3.times.map{@sighting.photos.build}

	end

	def update
		@sighting = Sighting.find(params[:id])
		if @sighting.update_attributes params[:sighting]
			redirect_to sightings_path
		else
			render :edit
		end
	end

	def destroy
		@sighting = Sighting.find(params[:id])
		@sighting.destroy
			redirect_to sightings_path
	end

	def show
		@sighting = Sighting.find(params[:id])
		@json = Sighting.find(params[:id]).to_gmaps4rails

	end


end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

	before_filter :authenticate_user!

	def new
		@topic = Topic.new

		
	end


	def create
		
		@topic = Topic.new params[:topic]
		#@topic.user = current_user
		#@topic = topics.build(params[:topic])
		if @topic.save
			redirect_to sightings_path
		else
			render 'new'
		end
	end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

	def twitter
		auth = env['omniauth.auth']
		uid = auth['uid']
		provider = auth['provider']

		user = User.where(uid: uid, provider: provider).first_or_create do |u|
			u.email = '#{uid}@twitter.com'
		end

		sign_in_and_redirect user
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/_comment.html.erb
<li>
	<%= comment.body %> | 
	Posted by: <%= comment.user.email %>
</li>

app/views/comments/_form.html.erb
<%= form_for [comment.sighting, comment] do |f| %>

	<%= f.text_field :body, placeholder: 'Add a comment' %>
	<%= f.submit %>
	
<% end %>

app/views/comments/new.html.erb
<%= render 'form', comment: @comment %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hacksighter1</title>

<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css" rel="stylesheet">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body 
	style = "background: #C5D2DB">
<body>

<!-- Added a Navbar - with title on LHS, and sign in/out next right, and username justified on RHS -->
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="/">HackSIGHTER</a>
	    <% if user_signed_in? %>
	    	<ul class = "nav pull-right">
		      	<li class="active">
		      	<%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
		    </ul>
		      	<div class='pull-right nav-user'>
		      		<p class = 'navbar-text'>
		      		<%= current_user.email %></p>
		      	</div>
		<% else %>
			<ul class="nav pull-right">
				<li class="active">
				<%= link_to "Sign In", new_user_session_path %></li></ul>
				<div class="pull-right nav-user">
					<p class= 'navbar-text'>
		      			Not signed in
		      		</p>
		      	</div>
		<% end %>

		<!-- Add searching to Navbar -->
			<!-- <form class = "navbar-form">
				<%#= search_form_for @q do |f| %>
				<%#= f.label :location_cont, "Search Location" %>
				<%#= f.text_field :location_cont, placeholder: "Location Keyword" %>

				<%#= f.label :topic_name_cont, "Search Topic" %>
				<%#= f.text_field :topic_name_cont, placeholder: "Topic Keyword" %>

				<%#= f.label :description_cont, "Description" %>
				<%#= f.text_field :description_cont, placeholder: "Description Keyword" %>

				<%#= button_tag(type: 'submit', class: "btn btn-info") do %>
				    <i class=#"icon-search icon-white"></i>
				  <%# end %>
			
				<%# end %>
			</form> -->

		<!-- End adding searching to Navbar -->
  </div>
</div>
<!-- End of Added Navbar -->

<div class='container'>



<%= yield %>

<%= yield :scripts %>

</body>
</html>

app/views/sightings/_form.html.erb
<%= form_for @sighting, html: {multipart: true, class: "form-horizontal"} do |f| %>
	
	<div class="control-group">
		<%= f.label :topic_id, class: "control-label" %>
		<div class="controls">
			<%= f.collection_select :topic_id, Topic.all, :id, :name %>
			<button class="btn" type="button"><%= link_to "Add a new topic?", new_topic_path %></button>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :description, class: "control-label" %>
		<div class="controls">
			<%= f.text_area :description, rows: "4", placeholder: 'Description' %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :location, class: 'control-label' %>
		<div class="controls">
			<%= f.text_field :location, placeholder: 'e.g.: 12 Kingsway W, Toronto' %>
		</div>	
	</div>

	<div class="control-group">
		<%= f.label :time, class: "control-label" %>
		<div class="controls">
		<%= f.text_field :sighted_date, class: "datepicker", placeholder: 'e.g.: 2012-01-04' %>
		<%= f.text_field :sighted_time, class: "timepicker", placeholder: 'e.g.: 12 pm' %>
		</div>	
	</div>

	<div class="control-group">
		<%= f.label :photos, class: "control-label" %>
		<div class="controls">

			<%= f.fields_for :photos, @photos do |builder| %>
				<div>
				<%#= builder.label :image %>
				<%= builder.file_field :image %>
				</div>
		<% end %>
		</div>
		
	<div class="control-group">
		<div class="controls">
			<%= f.submit 'Submit', class: "btn btn" %>
		</div>
	</div>

</form>
<% end %>

app/views/sightings/_infowindow.html.erb
<b><% topic_id = sighting.topic_id %> 
	<%= Topic.find(topic_id).name.upcase %></b></br> 
<%= sighting.description %></br>

<%= image_tag sighting.photos.first.image.url(:thumb) if sighting.photos.first %>

<b>Time: </b><%= sighting.sighted_at.to_formatted_s(:long) %></br>
<b>Spotter: </b><%= sighting.user.email %></br>
<b>Comments: </b><%= sighting.comments.count %></br>

	<% if sighting.user == @current_user %>
		<%= link_to 'Show', sighting %> |
		<%= link_to 'Edit', edit_sighting_path(sighting) %> |
		<%= link_to 'Destroy', sighting, method: :delete, data: { confirm: 'Are you sure?' } %>
	<% else %>
		<%= link_to 'Show', sighting %>
	<% end %>


<%#= render sighting.comments %>

<%#= render 'comments/form', comment: sighting.comments.build, sighting: sighting %>

app/views/sightings/edit.html.erb
<div class="container-fluid">

  <div class="row-fluid">
	<!--Original sighting, info, 1st row-->
 	<div class="span3">
		<b><%= Topic.find(@sighting.topic_id).name.upcase%></b><br />
		<em><%= @sighting.description %></em><br />
		<b> Location: </b>
				<%= @sighting.location %><br />
		<b> Time spotted: </b>
				<%= @sighting.sighted_at.to_formatted_s(:long) %><br />
 	</div>
 	<!--End original sighting, info, 1st row-->

 	<!--Original sighting, photos, 1st row-->
 	<div class="span9">

	<p>
		<% @sighting.photos.each do |photo| %>
			<%= image_tag photo.image.url(:thumb) if photo.image.present? %>
		<% end %>
	</p>
	</div>
	<!--End original sighting, photos, 1st row-->
  </div>

	<div class="row-fluid">
		<!--Edit form, 2nd row-->
	 	<div class="span6">

		<h3><p>Edit Sighting</p></h3>

		<%#= Topic.find(@sighting.topic_id).name%>
		<%= render 'form' %>

		</div>

		<div class="span 6">

			<p>
			<%= gmaps({
				"map_options" => {"auto_zoom" => false, "zoom" => 16 },
				"markers" => {"data" => @json}
				})
			%>
			</p>
		

		</div>
	</div>

</div>


<%= link_to 'Show', @sighting, class: "btn btn"%>
<%= link_to 'Back', sightings_path, class: "btn btn" %>

app/views/sightings/index.html.erb
<div class="container-fluid">
  
<!--1st row-->
  
<!--End of 1st row-->

<!--Start of 2nd row-->
  	<!--Sidebar content, 2nd row-->
  	<div class="row-fluid">
    	<div class="span3">
      
      		<p></p>
	      	<p><%= link_to "Report a sighting", new_sighting_path, class: "btn btn" %></p>		
	      	<p><%= link_to "Add a new topic", new_topic_path, class: "btn btn" %></p>

<!--Number of Sightings on Map (<%= @sightings.count %>)-->
<!-- <h3>Current User: 
	<#% if user_signed_in? %>
		<%#= current_user.email %>
	<%# else %>
		No User signed in
	<%# end %></h3>
 -->

<!--Searching--> 

	<p>
		<form class="form-horizontal">
			<%= search_form_for @q do |f| %>
				<%#= f.label :location_cont, "Search Location" %>
				<%= f.text_field :location_cont, placeholder: "Location Keyword" %>

				<%#= f.label :topic_name_cont, "Search Topic" %>
				<%= f.text_field :topic_name_cont, placeholder: "Topic Keyword" %>

				<%#= f.label :description_cont, "Description" %>
				<%= f.text_field :description_cont, placeholder: "Description Keyword" %>

				<%#= f.submit "Submit" %>
				<%= button_tag(type: 'submit', class: "btn btn-info") do %>
				    <i class="icon-search icon-white"></i>
				<% end %>
			<% end %>
		</form>
	</p>
	
	<!--End of searching-->


<!-- BELOW SECTION:  Ryan showed me way to make dropdown using css -->
	<%#= form_tag sightings_path, method: :get do %>
	<!-- 	<select name="topic">
			<option value="">
				<%#= link_to 'All sightings', sightings_path%> (<%#= @sightings_all.count %>)
			</option>
			<%# @topics.each do |topic| %>
				<option value="<%#= topic.id %>">
				<%#= topic.name%> (<%#= topic.sightings.count %> sightings)
				</option>
			<%# end %>
		</select>

		<input type='submit' value='Go!' />
	<%# end %>-->
<!-- END SECTION:  Ryan showed me way to make dropdown using css -->

<!--Can pick which topics to see on map-->

<div class="dropdown">
  <a class="dropdown-toggle btn btn-info" data-toggle="dropdown" href="#" >
  	SHOW SIGHTINGS
  	<b class="caret"></b>
  </a>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
    <li><%= link_to "ALL (#{@sightings_all.count})", sightings_path %></li>
    <li class = "divider"></li>
  
  	<% @topics.each do |topic| %>
		<li>
		<%= link_to "#{topic.name.upcase} (#{topic.sightings.count})", "?topic=#{topic.id}" %> 
		</li>
	<% end %>
  </ul>
</div>

<!--End picking which topics to see on map-->




<!-- <p>
<div class="dropdown">
  <a class="dropdown-toggle btn" data-toggle="dropdown" href="#" >
  	TOP 5
  	<b class="caret"></b>
  </a>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
    <li>Recent Sightings</li>
    <li>Topics</li>
    <li>Commented Sightings</li>
  </ul>
</div>
</p>
 -->
<!-- <p>
<b>Top 5</b>
	<%# @sightings_recent5.each do |recent5| %>
	<li><%# topic_id = recent5.topic_id %>
					<%#= Topic.find(topic_id).name.upcase %></li>
	<#% end %>
</p> -->
	</div>
	<!--End sidebar content, 2nd row-->

	<!--Main content, 2nd row-->
	<div class="span9">
		<%= gmaps("markers" => {"data" => @json, :options => { :do_clustering => true, randomize: true}}) %>

		<%#= gmaps("markers" => {"data" => @json, :options => { :raw => '{animation: google.maps.Animation.BOUNCE}'} }) %>

		<br />
		<div id="days-slider" style="width: 600px"></div>
		<input type="text" id="days-box" style="width: 590px", class="text-center" />
		<br />

		</ul>
		<script type="text/javascript">

                  function slider_display_string(from,to){
                    return " From " + Math.ceil(from/24)+ " to " + Math.floor(to/24) + " days ago "
                  }

		  now = new Date();
                  first_sight = new Date('<%= @sightings.first.sighted_at.to_s unless @sightings.empty?%>');
                  maxhours = Math.ceil((now.getTime()-first_sight.getTime())/3600000);
                  if (maxhours < 0 || maxhours > 24000 || isNaN(maxhours)) maxhours = 2400; 
                  //$ If more than maxhours, will default to 2400 hours 

		  $(document).ready(function() {
		    Gmaps.map.callback = function() {
		      var daysRange = {
		      min:-maxhours, 
		      max: 0,
		      };
		      $( "#days-box" ).val(slider_display_string(-daysRange.min, -daysRange.max));
		      $("#days-slider").slider({
		        range: true,
		        min: daysRange.min,
		        max: daysRange.max,
		        values: [ daysRange.min, daysRange.max ],

		        slide: function(event, ui) {
		          $( "#days-box" ).val( slider_display_string(-ui.values[0], -ui.values[1]));
		          //$( "#days-box" ).val( "filter: last " + Math.ceil(-ui.values[0]/24) + " days")
		      
		          $.each(Gmaps.map.markers, function(i, marker) {
		            var when = new Date(marker.when)
		            var hours = -(now.getTime()-when.getTime())/3600000;
		            if (hours < ui.values[0] || hours > ui.values[1]) Gmaps.map.hideMarker(marker)
		            if (hours >= ui.values[0] && hours <= ui.values[1]) Gmaps.map.showMarker(marker)
		          })

		        }
		      });
		    }
		  });
		</script>



		<p>
			<b><%= @topics.count %></b> <i class="icon-tags"></i><br />
			<b><%= @users.count %></b> <i class="icon-user"></i><br />
		</p>

	</div>
<!--End of 2nd row-->

<!--Start of 3rd row-->
<div class="row-fluid">
	<!--Table content, 3rd row-->
    <div class="span12">
    
	<div class="accordion" id="accordion2">
	  <div class="accordion-group">
	    <div class="accordion-heading">
	      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
	        <h4>MAP SIGHTINGS</h4>
	      </a>
	    </div>
	    <div id="collapseOne" class="accordion-body collapse in">
	      <div class="accordion-inner">
	       	<table class="table table-hover table-condensed">
				<thead>
					<tr>
						<th>TOPIC</th>
						<th>Description</th>
						<th>Location</th>
						<th>Time Spotted</th>
						<th>Spotter</th>			
						<th>Comments</th>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>
					<% @sightings.each do |sight| %>
					<tr>
						<td><% topic_id = sight.topic_id %>
							<%= Topic.find(topic_id).name.upcase %></td>
						<td><%= sight.description %></td>
						<td><%= sight.location %>
						<td><%= sight.sighted_at.to_formatted_s(:long) %></td>
						<td><%= sight.user.email %></td>
						<td><%= sight.comments.count %></td>
						<% if sight.user == @current_user %>
							<td><%= link_to 'Show', sight, class: "btn btn" %></td>
							<td><%= link_to 'Edit', edit_sighting_path(sight), class: "btn btn"%></td>
							<td><%= link_to 'Destroy', sight, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn" %></td>
						<% else %>
							<td><%= link_to 'Show', sight, class: "btn btn" %></td>
							<td></td>
							<td></td>
						<% end %>
					</tr>
				<% end %>
			</table>

	      </div>
	    </div>
	  </div>
	  </div>
	</div>
	</div>
    <!--End of table content-->

<%# @sightings.each do |sight| %>
	<!-- <ul>
	Posted by: <%#= sight.user.email %><br />
	Topic name: <%# topic_id = sight.topic_id %>
				<%#= Topic.find(topic_id).name %><br />
	Description: <%#= sight.description %><br />
	<%#= sight.location %>
	<%#= sight.longitude %>
	<%#= sight.latitude %>
	<%#= sight.sighted_at.to_formatted_s(:long) %><br />

	<%#= image_tag sight.photos.first.image.url if sight.photos.first %><br />
	
	<%#= link_to 'Show', sight %>
	<%#= link_to 'Edit', edit_sighting_path(sight) %>
	<%#= link_to 'Destroy', sight, method: :delete, data: { confirm: 'Are you sure?' } %>
	
	</ul>


		<%#= render sight.comments %>
		<li>
			<%#= render 'comments/form',
					comment: sight.comments.build,
					sighting: sight %>
		</li>
	</ul>

	</li>
<%# end %>
</ul>
 -->
<!--Main content-->

<!--End of 3rd row-->
</div>
</div>

app/views/sightings/new.html.erb
<h3>Report a New Sighting</h3>

<% if @sighting.errors.any? %>
		<h2 style="color:red">Something went wrong</h2>
			<ul>
				<% @sighting.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', sightings_path, class: 'btn btn' %>

app/views/sightings/show.html.erb
<div class="container-fluid">

  <div class="row-fluid">
 	<!--Photo content, 1st row-->
 	<div class="span12">
 		<p>
		<% @sighting.photos.each do |photo| %>
			<%= image_tag photo.image.url(:large) %>
		<% end %>
		</p>
 	</div>
 	<!--End photo content, 1st row-->
  </div>


  <div class="row-fluid">
    <!--Sidebar content, 2nd row-->
    <div class="span3">
		<p>
			<h3><%= Topic.find(@sighting.topic_id).name.upcase%></h3>
			<p class = "lead" "text-center"><%= @sighting.description %></p>
		</p>
		
		<p>
			<b> Location </b>
				<%= @sighting.location %>
		</p>

		<!--
		<p>
			<b> Longitude </b>
				<%= @sighting.longitude %>
		</p>
		<p>
			<b> Latitude </b>
				<%= @sighting.latitude %>
		</p>
		-->

		<p>
			<b> Time spotted </b>
				<%= @sighting.sighted_at.to_formatted_s(:long) %>
		</p>

		<p>
			<b> Spotted by: </b>
				<%= @sighting.user.email %>
		</p>
	</div>
    <!--End sidebar content, 2nd row-->

    <!--Main content, 2nd row-->
    <div class="span9">    
		<p>
		<%= gmaps({
				"map_options" => {"auto_zoom" => false, "zoom" => 16 },
				"markers" => {"data" => @json}
				})
			%>
		</p>
	</div>
	<!-- End main content, 2nd row-->

	  </div>
	</div>

<div class="row-fluid">
	 <!--Comments, 3rd row-->
    <div class="span12">
		<h4> COMMENTS </h4>
		<%= render @sighting.comments %>

		<%= render 'comments/form', comment: @sighting.comments.build, sighting: @sighting %>  
	</div>
	 <!--End comments, 3rd row-->

</div>


<%= link_to 'Back', sightings_path, class: 'btn btn' %>

app/views/topics/_form.html.erb
<%= form_for @topic, class: "form-horizontal" do |f| %>

<div class="control-group">
	<%= f.text_field :name, class: "control-label", placeholder: 'Add a topic' %>
		
	<div class="control-group">
		<%= f.submit%>
	</div>
</div>

<% end %>

<%= link_to 'Back', sightings_path, class: 'btn btn' %>

app/views/topics/new.html.erb
<h3>Add a New Topic</h3>


<%= render 'form' %>